app_modules/users/urls.py
from django.urls import path
from app_modules.users import views

app_name = 'users'

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('admin/', views.UserListView.as_view(), name='admin_list'),
    path('student/', views.StudentListView.as_view(), name='student_list'),
    path('teacher/', views.TeacherListView.as_view(), name='teacher_list'),
    path('delete', views.UserDeleteAjaxView.as_view(), name='delete_user'),
    path('add/admin/', views.AdminCreateView.as_view(), name='add_user_form'),
    path('add/teacher/', views.TeacherCreateView.as_view(), name='add_teacher_form'),
    path('add/student/', views.StudentCreateView.as_view(), name='add_student_form'),
    path('<str:encoded_id>/update', views.UserUpdateView.as_view(), name='update_user'),
    path('<str:encoded_id>/details', views.UserDetailsView.as_view(), name='user_details'),
    path('user_list_ajax', views.UserDataTablesAjaxPagination.as_view(), name='user_list_ajax'),
]

lms_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from app_modules.users.views import DashboardView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("accounts/", include("allauth.urls")),
    path('accounts/', include('allauth.socialaccount.urls')),
    path("users/", include("app_modules.users.urls")),
    path("courses/", include("app_modules.course.urls")),
    path("",DashboardView.as_view(), name="dashboard"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_modules/users/models.py
from django.db import models
from django.utils.encoding import force_bytes
from django.contrib.auth.models import AbstractUser
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _

from app_modules.base.utils import normalize_email

class CustomManager(models.Manager):

    """
    Custom manager for filtering objects based on their status.

    This manager provides custom methods to filter model instances based on
    their `status` field. It includes methods for getting all active instances
    and filtering active instances with additional criteria.
    """

    def active_all(self):
        return super().get_queryset().filter(status='Active')
    
    def active_filter(self, **kwargs):
        return self.get_queryset().filter(status='Active', **kwargs)
    
    def get_by_natural_key(self, email):
        return self.get_queryset().get(email=email)
    
    def normalize_email(self,email):
        """
        Normalize the email address by lowercasing the domain part of it.
        """
        return normalize_email(email)

    def create_superuser(self, email, password=None, **extra_fields):
        """Creates and returns a superuser."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)
    
    def create_user(self, email, password=None, **extra_fields):
        """Creates and returns a regular user."""
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        extra_fields.setdefault("is_active", True)  # Ensure user is active by default
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
        

class User(AbstractUser):

    """
    Custom User model that extends the default Django User model.

    This model adds additional fields for handling the user's role, 
    profile image, mobile number, and account status.
    """

    ACTIVE   = "Active"
    INACTIVE = "Inactive"

    STATUS_CHOICES = (
        (ACTIVE, ACTIVE),
        (INACTIVE, INACTIVE),
    )

    SUPER_ADMIN = "Super Admin"
    TEACHER     = "Teacher"
    STUDENT     = "Student"

    USER_ROLE = (
        (SUPER_ADMIN, SUPER_ADMIN),
        (TEACHER, TEACHER),
        (STUDENT, STUDENT),
    )

    email   = models.EmailField(_('Email'), unique=True)
    image   = models.ImageField(upload_to="users/profile pic/", null=True, blank=True)
    mobile  = models.CharField(_('Mobile'), max_length=15, null=True, blank=True)
    role    = models.CharField(_('Role'), choices=USER_ROLE, null=True, blank=True, max_length=100)
    status  = models.CharField(_('Status'), choices=STATUS_CHOICES, default=ACTIVE, max_length=100)
    objects = CustomManager()

    def __str__(self):
        return self.get_full_name().title() or self.username.title()
    
    def get_encoded_id(self):
        return urlsafe_base64_encode(force_bytes(self.pk))

class StudentManager(models.Manager):
    """
    Custom manager for filtering Student users.
    """
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=User.STUDENT)
    
    def normalize_email(self,email):
        """
        Normalize the email address by lowercasing the domain part of it.
        """
        return normalize_email(email)

class Students(User):
    """
    Proxy model for the 'Student' user.
    """
    role    = User.STUDENT
    objects = StudentManager()

    class Meta:
        proxy = True
        verbose_name = 'Student'
        verbose_name_plural = 'Students'  

    def __str__(self):
        return self.get_full_name().title() or self.username.title()
    

class TeacherManager(models.Manager):
    """
    Custom manager for filtering Teacher users.
    """
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=User.TEACHER)
    
    def normalize_email(self,email):
        """
        Normalize the email address by lowercasing the domain part of it.
        """
        return normalize_email(email)

class Teachers(User):
    """
    Proxy model for the 'Teacher' user.
    """
    role    = User.TEACHER
    objects = TeacherManager()

    class Meta:
        proxy = True
        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'  

    def __str__(self):
        return self.get_full_name().title() or self.username.title()

class SAdminManager(models.Manager):
    """
    Custom manager for filtering Admin users.
    """
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=User.SUPER_ADMIN)
    
    def normalize_email(self,email):
        """
        Normalize the email address by lowercasing the domain part of it.
        """
        return normalize_email(email)

class SuperAdmin(User):
    """
    Proxy model for the 'Super Admin' user.
    """
    role    = User.SUPER_ADMIN
    objects = SAdminManager()

    class Meta:
        proxy = True
        verbose_name = 'SuperAdmin'
        verbose_name_plural = 'SuperAdmins'  

    def __str__(self):
        return self.get_full_name().title() or self.username.title()

app_modules/users/views.py
from django.db.models import Q
from app_modules.users import tasks
from app_modules.users import models
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils.encoding import force_str
from allauth.account.views import LogoutView
from django.urls import reverse , reverse_lazy
from django.shortcuts import get_object_or_404
from django.template.loader import get_template
from app_modules.users.user_forms import UserForm
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import get_user_model,logout
from django_datatables_too.mixins import DataTableMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from app_modules.base.utils import get_encoded_id,get_actions_buttons
from django.views.generic import TemplateView,View,UpdateView,DetailView
from app_modules.base.views import BaseDeleteAjaxView, BaseListView, BaseCreateView

User = get_user_model()

class DashboardView(LoginRequiredMixin,TemplateView):
    
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        ctx =  super().get_context_data(**kwargs)
        ctx['current_page'] = "Dashboard"
        return ctx

class UserListView(BaseListView):

    template_name = "users/list.html"
    queryset = models.SuperAdmin.objects.all()

    def get_table_name(self):
        return "Admin"
    
    def get_user_type(self):
        return User.SUPER_ADMIN
    
    def get_create_url(self):
        return reverse('users:add_user_form')

class StudentListView(BaseListView):

    template_name = "users/list.html"
    queryset = models.SuperAdmin.objects.all()

    def get_table_name(self):
        return User.STUDENT

    def get_user_type(self):
        return User.STUDENT
    
    def get_create_url(self):
        return reverse('users:add_student_form')

class TeacherListView(BaseListView):

    template_name = "users/list.html"
    queryset = models.SuperAdmin.objects.all()

    def get_table_name(self):
        return User.TEACHER
    
    def get_user_type(self):
        return User.TEACHER
    
    def get_create_url(self):
        return reverse('users:add_teacher_form')
   
class BaseUserCreateView(BaseCreateView):

    """Base User Create View to handle common logic for all user roles."""

    model = User
    password = "test@123" 
    form_class = UserForm
    template_name = "users/user_form.html"

    def get_user_role(self):
        """Method to be overridden in subclasses to set user role."""
        raise NotImplementedError

    def get_role_specific_data(self):
        """Method to return role-specific data for breadcrumbs and current page."""
        raise NotImplementedError

    def form_valid(self, form):
        user = form.save(commit=False)
        user.role = self.get_user_role()  
        user.set_password(self.password)
        user.save()
        tasks.send_email_notifications.delay()
        task_obj = tasks.SendUserCredentialsEmail()
        task_obj.apply_async(args=[user.id, self.password])
        return super().form_valid(form)

    def get_current_page_name(self):
        return self.get_role_specific_data()['current_page']

    def get_breadcrumb_name(self):
        return self.get_role_specific_data()['breadcrumb_name']

    def get_breadcrumb_url(self):
        return self.get_role_specific_data()['breadcrumb_url']

class AdminCreateView(BaseUserCreateView):

    """Admin Create View."""

    success_url = reverse_lazy('users:admin_list')
    
    def get_user_role(self):
        return User.SUPER_ADMIN

    def get_role_specific_data(self):
        return {
            'current_page': "Admin",
            'breadcrumb_name': "Admin",
            'breadcrumb_url': reverse_lazy('users:admin_list')
        }

class TeacherCreateView(BaseUserCreateView):

    """Teacher Create View."""

    success_url = reverse_lazy('users:teacher_list')

    def get_user_role(self):
        return User.TEACHER

    def get_role_specific_data(self):
        return {
            'current_page': User.TEACHER,
            'breadcrumb_name': User.TEACHER,
            'breadcrumb_url': reverse_lazy('users:teacher_list')
        }

class StudentCreateView(BaseUserCreateView):

    """Student Create View."""
    
    success_url = reverse_lazy('users:student_list')

    def get_user_role(self):
        return User.STUDENT

    def get_role_specific_data(self):
        return {
            'current_page': User.STUDENT,
            'breadcrumb_name': User.STUDENT,
            'breadcrumb_url': reverse_lazy('users:student_list')
        }

class UserUpdateView(LoginRequiredMixin,UpdateView):

    model = User
    form_class = UserForm
    template_name = "users/user_form.html"

    def get_object(self, queryset=None):

        return get_object_or_404(User, id=force_str(urlsafe_base64_decode(self.kwargs['encoded_id'])))

    def get_context_data(self, **kwargs):

        ctx = super().get_context_data(**kwargs)
        obj = self.get_object()

        role_mapping = {
            User.SUPER_ADMIN: ("Update Admin", "Admin", reverse('users:admin_list')),
            User.TEACHER: ("Update Teacher", "Teacher", reverse('users:teacher_list')),
            User.STUDENT: ("Update Student", "Student", reverse('users:student_list')),
        }

        current_page, page_name, breadcrumb_url = role_mapping.get(obj.role)

        ctx.update({
            'current_page': current_page,
            'page_name': page_name,
            'breadcrumbs': [
                {"name": "Dashboard", "url": reverse_lazy('dashboard')},
                {"name": page_name, "url": breadcrumb_url},
            ]
        })
        
        return ctx
    
    def get_success_url(self):

        role_to_url = {
            User.SUPER_ADMIN: 'users:admin_list',
            User.TEACHER: 'users:teacher_list',
            User.STUDENT: 'users:student_list',
        }
        return reverse_lazy(role_to_url.get(self.object.role)) 
        
class UserDetailsView(LoginRequiredMixin,DetailView):

    model = User
    pk_url_kwarg = 'encoded_id'
    context_object_name = 'user'
    template_name = "users/user_details.html"

    def get_object(self):

        encoded_pk = self.kwargs.get(self.pk_url_kwarg)
        user_id = force_str(urlsafe_base64_decode(encoded_pk))
        return get_object_or_404(User, id=user_id)
    
    def get_context_data(self, **kwargs):

        ctx =  super().get_context_data(**kwargs)
        ctx['breadcrumbs'] = [
            {"name": "Pages", "url": "javascript:;"},
        ]
        ctx["current_page"] = self.get_object().get_full_name()
        return ctx
    
class UserDeleteAjaxView(BaseDeleteAjaxView):

    """User Delete View"""
    
    model = User  
    
class UserDataTablesAjaxPagination(LoginRequiredMixin,DataTableMixin, View):

    """User Datatable View"""

    model = User

    def get_queryset(self):

        qs = User.objects.all()
        role = self.request.GET.get("role")
        if role:
            qs = qs.filter(role=role)
        return self.filter_queryset(qs)

    def _get_actions(self, obj):

        delete_url = reverse('users:delete_user')
        update_url = reverse('users:update_user', kwargs={'encoded_id': get_encoded_id(obj.id)})
        return get_actions_buttons(update_url,delete_url,obj.get_full_name(),get_encoded_id(obj.id))

    def filter_queryset(self, qs):

        if self.search:
            return qs.filter(
                Q(first_name__icontains=self.search) |
                Q(last_name__icontains=self.search) | 
                Q(email__icontains=self.search) | 
                Q(mobile__icontains=self.search)
            )
        return qs
    
    def _get_full_name(self,obj):

        t = get_template("users/get_full_name.html")
        context = {
            "obj": obj,
        }
        return t.render(context)

    def prepare_results(self, qs):

        data = []
        for o in qs:
            data.append(
                {
                    "id": o.id,
                    "full_name": self._get_full_name(o),
                    "mobile": o.mobile if o.mobile else "-----",
                    "actions": self._get_actions(o),
                }
            )
        return data

    def get(self, request, *args, **kwargs):

        context_data = self.get_context_data(request)
        return JsonResponse(context_data)
   
class LogoutView(LoginRequiredMixin,LogoutView):

    def get(self, request):
        logout(self.request)
        return redirect("/accounts/login")

templates/users/get_full_name.html
{% load static %}

<div class="d-flex align-items-center">
    {% if obj.image %}
        <img src="{{ obj.image.url }}" alt="User Image" class="rounded-circle" style="width: 30px; height: 30px; object-fit: cover; margin-right: 10px;">
    {% else %}
        <img src="{% static 'images/default-avatar.png' %}" alt="User Image" class="rounded-circle" style="width: 30px; height: 30px; object-fit: cover; margin-right: 10px;">
    {% endif %}
    
    <a href="{% url 'users:user_details' encoded_id=obj.get_encoded_id %}">
        <span>{{ obj.first_name }} {{ obj.last_name }}</span>
    </a>
</div>

templates/users/list.html
{% extends "common/base.html" %}
{% load static %}

{% block title %} 
    {{current_page}} List
{% endblock title %}

{% block main %}
<div class="row">
    <div class="col-12">
      <div class="card shadow mb-4">
        <div class="card-header pb-0 d-flex justify-content-between">
          <h6>{{ table_name }} Table</h6>
          <a href="{{create_url}}">
            <button type="button" class="btn btn-primary">Add</button>
          </a>
        </div>
        <div class="card-body">
          <div class="table-responsive p-2">
            <table class="table table-striped border-top border-bottom" id="user_table">
              <thead>
                <tr>
                  <th>SR NO.</th>
                  <th>Full name</th>
                  <th>Mobile</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
  
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock main %}

{% block script %}

<!-- for sweet alert for deleting object  -->
<script src="{% static 'assets/js/delete_element.js' %}"></script>
<!-- for sweet alert for deleting object  -->

<!-- for datatable  -->
<script src="{% static 'assets/datatables/initialize_datatables.js' %}"></script>
<script src="{% static 'assets/datatable/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/datatable/dataTables.bootstrap4.min.js' %}"></script>
<script>
	var element_table_id = '#user_table'
  var user_type = "{{ user_type|safe }}";
  var role = true;
  var i = 1;
  var table_id = element_table_id
  var filter_id = $("#id_company,#id_role")
  var to_center = "_all"
  var invisible_columns = []
  var order_false = [-1]
  var url = '{% url "users:user_list_ajax" %}'
  var columns = [
    { data: 'id', name: 'id' },
    { data: 'full_name', name: 'first_name' },
    { data: 'mobile', name: 'mobile' },
    { data: 'actions', name: 'actions' }
  ]

  function set_filters() {
    var data = {}
    data["role"] = user_type;
    return data;
  }

  initialize_datatables();

  $(document).ready(function (){
    $("#user_table_filter").addClass("mb-2")
  });
</script>
<!-- for datatable  -->

{% endblock script %}

templates/users/user_form.html
{% extends 'common/base.html' %}
{% load static crispy_forms_tags %}

{% block title %}
  {{ current_page }}
{% endblock %}

{% block main %}
  <div class="row">
    <div class="col-12">
      <div class="card shadow mb-4">
        <div class="card-header pb-0 d-flex justify-content-between">
          {% if form.instance.pk %}
            <h2>Update {{ page_name }}</h2>
          {% else %}
            <h2>Create A New {{ page_name }}</h2>
          {% endif %}
        </div>

        <hr style="border: 1px solid #ccc; margin-top: 10px; margin-bottom: 10px; " />

        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <hr style="border: 1px solid #ccc; margin-top: 10px; margin-bottom: 10px;" />

            <div class="row">
              <div class="col-6">
                <div class="form-group">{{ form.first_name|as_crispy_field }}</div>
              </div>
              <div class="col-6">
                <div class="form-group">{{ form.last_name|as_crispy_field }}</div>
              </div>
            </div>

            <hr style="border: 1px solid #ccc; margin-top: 10px; margin-bottom: 10px;" />

            <div class="row">
              <div class="col-6">
                <div class="form-group">{{ form.username|as_crispy_field }}</div>
              </div>
              <div class="col-6">
                <div class="form-group">{{ form.email|as_crispy_field }}</div>
              </div>
            </div>

            <hr style="border: 1px solid #ccc; margin-top: 10px; margin-bottom: 10px;" />

            <div class="row">
              <div class="col-6">
                <div class="form-group">{{ form.mobile|as_crispy_field }}</div>
              </div>

              <div class="col-6">
                <div class="form-group d-flex justify-content-between">
                  {% if form.instance.image %}
                    <div class="current-image avatar avatar-xl position-relative">
                      <img src="{{ form.instance.image.url }}" alt="Selected Image" style="max-width: 80px; max-height: 80px;" />
                    </div>
                  {% endif %}
                  {{ form.image|as_crispy_field }}
                </div>
              </div>
            </div>

            <hr style="border: 1px solid #ccc; margin-top: 10px; margin-bottom: 10px;" />

            <div class="row">
              <div class="col-6">
                <div class="form-group">
                  {{ form.captcha }}
                  {% if form.captcha.errors %}
                    <div class="error">{{ form.captcha.errors }}</div>
                  {% endif %}
                </div>
              </div>
            </div>

            <hr style="border: 1px solid #ccc; margin-top: 10px; margin-bottom: 10px;" />

            <button type="submit" class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $(document).ready(function () {
      $('#image-clear_id').hide()
      $("label[for='image-clear_id']").hide()
    })
  </script>
{% endblock %}